version: '3.3'

services:
    api:
        container_name: filesharing_api_dev
        # image: filesharing-api-dev:1.0.0
        build:
         context: ./server
         dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
          - 3000:3000
        networks:
          - filesharing-network
        volumes:
          - ./server:/usr/src/app/server
          - /usr/src/app/server/node_modules
        links:
          - mysql_db:database
        depends_on:
          - mysql_db
        restart: unless-stopped
    mysql_db:
        container_name: mysql_dev
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
        networks:
          - filesharing-network
        restart: unless-stopped
        environment:
          MYSQL_DATABASE: 'filesharing'
          # Password for root access
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
          - '3306:3306'
        expose:
          - '3306'
        volumes:
          - my-db:/var/lib/mysql
    client:
      build:
       context: ./client
       dockerfile: ./Dockerfile
      networks:
          - filesharing-network
      ports:
        - "8080:8080"
      container_name: vue-ui
      links:
        - api:server
      restart: unless-stopped
      depends_on:
        - api
      command: npm run serve
      volumes:
        - ./client:/usr/src/app/client
        - /usr/src/app/client/node_modules
networks:
  filesharing-network:
volumes:
    my-db:
